version: 0.2
# Environment variables we inject via Terraform
# 905418423035.dkr.ecr.eu-west-1.amazonaws.com/mini-erp)

phases:
  # -----------------------------------------------------
  # 1. Install
  # -----------------------------------------------------
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Docker Login...
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

  # -----------------------------------------------------
  # 2. PRE-BUILD (Login and preparation)
  # -----------------------------------------------------
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION

  # -----------------------------------------------------
  # 3. BUILD
  # -----------------------------------------------------
  build:
    commands:
#      - echo Running Maven clean package...
#      - mvn clean package
      - echo Running Maven clean install...
      - mvn clean install -DskipTests
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_URI:latest -t $ECR_REPO_URI:$IMAGE_TAG .

  # -----------------------------------------------------
  # 4. AFTER BUILD - vulnerability scanner
  # -----------------------------------------------------
  post_build:
    commands:
#      - echo Running security scan with Trivy...
#      - trivy image --exit-code 1 --severity CRITICAL $ECR_REPO_URI:latest

      - echo Pushing the Docker images...
      - docker push $ECR_REPO_URI:latest
      - docker push $ECR_REPO_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'