version: 0.2
# Environment variables we inject via Terraform
# 905418423035.dkr.ecr.eu-west-1.amazonaws.com/mini-erp

phases:
  # -----------------------------------------------------
  # 1. Install
  # -----------------------------------------------------
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Docker Login...
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - apt-get update && apt-get install -y jq

  # -----------------------------------------------------
  # 2. PRE-BUILD (Login and preparation)
  # -----------------------------------------------------
  pre_build:
    commands:
      # Login ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION

#      # Login Docker Hub by variables
#      - echo Logging in to Docker Hub securely..
#      - echo "$DOCKER_PAT" | docker login --username "$DOCKER_USER" --password-stdin

      # Login Docker Hub using Secrets Manager
      - echo "Logging in to Docker Hub securely..."
      - export DOCKER_CREDS=$(aws secretsmanager get-secret-value --secret-id dockerhub-secret-name --query SecretString --output text)
      - export DOCKER_USER=$(echo $DOCKER_CREDS | jq -r '.username')
      - export DOCKER_PAT=$(echo $DOCKER_CREDS | jq -r '.password')
      - echo $DOCKER_PAT | docker login --username $DOCKER_USER --password-stdin


  # -----------------------------------------------------
  # 3. BUILD
  # -----------------------------------------------------
  build:
    commands:
      - echo Running Maven clean install and executing all tests...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_URI:latest -t $ECR_REPO_URI:$IMAGE_TAG .

  # -----------------------------------------------------
  # 4. POST-BUILD - vulnerability scanner
  # -----------------------------------------------------
  post_build:
    commands:
      # Security scan with Trivy (optional)
      # To enable later, uncomment the two lines below:
      # - echo Running security scan with Trivy...
      # - trivy image --exit-code 1 --severity CRITICAL $ECR_REPO_URI:latest
      - echo Pushing the Docker images...
      - docker push $ECR_REPO_URI:latest
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo Writing image definitions file with commit tag:$IMAGE_TAG
      - printf '[{"name":"mini-erp","imageUri":"%s"}]' $ECR_REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json