# src/main/resources/application-prod.properties

spring.application.name=Mini-ERP

# -----------------------------------------------------
# Database settings (local)
# -----------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://minierp-postgres-db.cdo6c2kyu0bn.eu-west-1.rds.amazonaws.com:5432/minierp-postgres-db
spring.datasource.username=postgres
spring.datasource.password=T5ui>)tP4Hge4~BnK#*1bIvJ#3EX
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# -----------------------------------------------------
# DATADOG
# -----------------------------------------------------
management.datadog.metrics.export.enabled=false



