# src/main/resources/application-prod.properties

spring.application.name=Mini-ERP

# -----------------------------------------------------
# Database settings (PROD)
# -----------------------------------------------------
spring.jpa.hibernate.ddl-auto=update


# -----------------------------------------------------
# DATADOG
# -----------------------------------------------------
management.datadog.metrics.export.enabled=false



