# src/main/resources/application.properties

spring.application.name=Mini-ERP

# -----------------------------------------------------
# Database settings (local)
# -----------------------------------------------------
spring.jpa.hibernate.ddl-auto=update



# -----------------------------------------------------
# DATADOG
# -----------------------------------------------------
management.datadog.metrics.export.enabled=false


# 1. Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. URL de Conexão: Usa a variável injetada DB_ENDPOINT (que não criamos, mas usaremos)
#    Nota: O Spring Boot permite usar "${}" para referenciar variáveis de ambiente
spring.datasource.url=jdbc:postgresql://minierp-postgres-db.cdo6c2kyu0bn.eu-west-1.rds.amazonaws.com:5432/minierp-postgres-db

# 3. Credenciais: Usa as variáveis injetadas
spring.datasource.username=postgres
spring.datasource.password=T5ui>)tP4Hge4~BnK#*1bIvJ#3EX

# (Opcional) Configurações do Pool de Conexão
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000