# src/main/resources/application-dev.properties

server.port=8081

# -----------------------------------------------------
# Database settings --> ENV DEV
# -----------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/mini-erp
spring.datasource.username=root
spring.datasource.password=Brasil2024


# -----------------------------------------------------
# Datadog --> ENV DEV
# -----------------------------------------------------
management.datadog.metrics.export.enabled=false




