# src/main/resources/application-prod.properties

spring.application.name=Mini-ERP

# -----------------------------------------------------
# Database settings (PROD)
# -----------------------------------------------------
#spring.datasource.url=jdbc:postgresql://minierp-postgres-db.cdo6c2kyu0bn.eu-west-1.rds.amazonaws.com:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=devopssec
#spring.datasource.hikari.data-source-properties.ssl=true
#spring.datasource.hikari.data-source-properties.sslmode=require
#spring.jpa.hibernate.ddl-auto=validate

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.jpa.hibernate.ddl-auto=validate

# -----------------------------------------------------
# DATADOG
# -----------------------------------------------------
management.datadog.metrics.export.enabled=false



