spring.application.name=Mini-ERP

# DataDog
management.datadog.metrics.export.enabled=true

# -----------------------------------------------------
# Database settings (local)
# -----------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/mini-erp
spring.datasource.username=root
spring.datasource.password=Brasil2024
spring.jpa.hibernate.ddl-auto=update