# src/main/resources/application.properties

spring.application.name=Mini-ERP

# -----------------------------------------------------
# Database settings (local)
# -----------------------------------------------------
spring.jpa.hibernate.ddl-auto=update



# -----------------------------------------------------
# DATADOG
# -----------------------------------------------------
management.datadog.metrics.export.enabled=false